export interface SeedExercise {
  name: string;
  muscle_group: string;
  warmup_sets: number;
  working_sets: number;
  target_reps: string;
  target_rpe: string;
  rest_seconds: number;
  notes: string;
  is_superset?: number;
  superset_group?: string;
}

export interface SeedWorkout {
  name: string;
  day_type: string;
  exercises: SeedExercise[];
}

export interface SeedPhase {
  name: string;
  description: string;
  workouts: SeedWorkout[];
}

export const SEED_DATA: SeedPhase[] = [
  {
    name: 'Phase 1',
    description: 'Base Hypertrophy (Moderate Volume, Moderate Intensity)',
    workouts: [
      {
        name: 'Push #1',
        day_type: 'push',
        exercises: [
          {
            name: 'Bench Press',
            muscle_group: 'Chest',
            warmup_sets: 3,
            working_sets: 1,
            target_reps: '3-5',
            target_rpe: '8-9',
            rest_seconds: 210,
            notes: 'Set up a comfortable arch, quick pause on the chest and explode up on each rep',
          },
          {
            name: 'Larsen Press',
            muscle_group: 'Chest',
            warmup_sets: 0,
            working_sets: 2,
            target_reps: '10',
            target_rpe: '8-9',
            rest_seconds: 210,
            notes: 'Shoulder blades still retracted and depressed. Slight arch in upper back. Zero leg drive.',
          },
          {
            name: 'Standing Dumbbell Arnold Press',
            muscle_group: 'Shoulders',
            warmup_sets: 2,
            working_sets: 3,
            target_reps: '8-10',
            target_rpe: '8-9',
            rest_seconds: 150,
            notes: 'Start with your elbows in front of you and palms facing in. Rotate the dumbbells so that your palms face forward as you press.',
          },
          {
            name: 'A1. Press-Around',
            muscle_group: 'Chest',
            warmup_sets: 1,
            working_sets: 2,
            target_reps: '12-15',
            target_rpe: '9-10',
            rest_seconds: 0,
            notes: 'Brace with your non-working arm, squeeze your pecs by pressing the cable across your body',
            is_superset: 1,
            superset_group: 'A',
          },
          {
            name: 'A2. Pec Static Stretch',
            muscle_group: 'Chest',
            warmup_sets: 0,
            working_sets: 2,
            target_reps: '30s HOLD',
            target_rpe: '7',
            rest_seconds: 90,
            notes: 'Hold a pec stretch for 30 seconds. The stretch should be held at about a 7/10 intensity.',
            is_superset: 1,
            superset_group: 'A',
          },
          {
            name: 'Cross-Body Cable Y-Raise',
            muscle_group: 'Shoulders',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '12-15',
            target_rpe: '9-10',
            rest_seconds: 90,
            notes: 'Think about swinging the cable out and up as if "drawing a sword" from your side',
          },
          {
            name: 'Triceps Pressdown + Overhead Extension',
            muscle_group: 'Triceps',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '8 + 8',
            target_rpe: '9-10',
            rest_seconds: 90,
            notes: 'Do the second half of the ROM for pressdowns ("the squeeze") and the first half of the ROM for overhead extensions ("the stretch")',
          },
          {
            name: 'N1-Style Cross-Body Triceps Extension',
            muscle_group: 'Triceps',
            warmup_sets: 0,
            working_sets: 2,
            target_reps: '10-12',
            target_rpe: '10',
            rest_seconds: 90,
            notes: 'Extend your triceps with your arm more out to the side than a regular pressdown. Feel the stretch as the cable moves across your torso',
          },
        ],
      },
      {
        name: 'Pull #1',
        day_type: 'pull',
        exercises: [
          {
            name: 'Lat Pulldown (Feeder Sets)',
            muscle_group: 'Back',
            warmup_sets: 0,
            working_sets: 4,
            target_reps: '10',
            target_rpe: '4-8',
            rest_seconds: 150,
            notes: 'Do 4 feeder sets of 10 reps by gradually building the weight up. Set 1: RPE 4-5. Set 2: RPE 6-7. Set 3: RPE 7-8. Set 4: Try to hit failure at 10 reps.',
          },
          {
            name: 'Lat Pulldown (Failure + Dropset)',
            muscle_group: 'Back',
            warmup_sets: 0,
            working_sets: 1,
            target_reps: '10+5',
            target_rpe: '10',
            rest_seconds: 150,
            notes: 'After hitting failure at ~10 reps, do a dropset. Strip the weight back ~30-50% and do another 5 reps with nice and controlled technique',
          },
          {
            name: 'Omni-Grip Machine Chest-Supported Row',
            muscle_group: 'Back',
            warmup_sets: 2,
            working_sets: 3,
            target_reps: '10-12',
            target_rpe: '8-9',
            rest_seconds: 150,
            notes: 'Use 3 different grips for the 3 working sets (ideally going from wider to closer)',
          },
          {
            name: 'A1. Bottom-Half DB Lat Pullover',
            muscle_group: 'Back',
            warmup_sets: 1,
            working_sets: 2,
            target_reps: '10-12',
            target_rpe: '9-10',
            rest_seconds: 0,
            notes: 'Do DB lat pullovers, but cut out the top half of the ROM (stay entirely in the stretched aspect of the lift)',
            is_superset: 1,
            superset_group: 'A',
          },
          {
            name: 'A2. Lat Static Stretch',
            muscle_group: 'Back',
            warmup_sets: 0,
            working_sets: 2,
            target_reps: '30s HOLD',
            target_rpe: '7',
            rest_seconds: 90,
            notes: 'Hold a lat stretch for 30 seconds. The stretch should be held at about a 7/10 intensity.',
            is_superset: 1,
            superset_group: 'A',
          },
          {
            name: 'Omni-Direction Face Pull',
            muscle_group: 'Rear Delts',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '12-15',
            target_rpe: '9-10',
            rest_seconds: 90,
            notes: '1st set: low-to-high\n2nd set: mid-range\n3rd set: high-to-low',
          },
          {
            name: 'EZ-Bar Curl',
            muscle_group: 'Biceps',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '6-8',
            target_rpe: '9-10',
            rest_seconds: 90,
            notes: 'Focus on contracting your biceps, minimize torso momentum',
          },
          {
            name: 'Bottom-Half Preacher Curl',
            muscle_group: 'Biceps',
            warmup_sets: 0,
            working_sets: 2,
            target_reps: '10-12',
            target_rpe: '10',
            rest_seconds: 90,
            notes: 'Do preacher curls, but cut out the top half of the ROM (stay entirely in the stretched aspect of the lift)',
          },
        ],
      },
      {
        name: 'Legs #1',
        day_type: 'legs',
        exercises: [
          {
            name: 'Squat',
            muscle_group: 'Quads',
            warmup_sets: 3,
            working_sets: 1,
            target_reps: '2-4',
            target_rpe: '8-9',
            rest_seconds: 210,
            notes: 'Sit back and down, keep your upper back tight to the bar',
          },
          {
            name: 'Pause Squat (Back Off)',
            muscle_group: 'Quads',
            warmup_sets: 0,
            working_sets: 2,
            target_reps: '5',
            target_rpe: '8-9',
            rest_seconds: 210,
            notes: 'Drop the weight by ~25% from your top set. 2 second pause. Sit back and down, keep your upper back tight to the bar',
          },
          {
            name: 'Barbell RDL',
            muscle_group: 'Hamstrings',
            warmup_sets: 2,
            working_sets: 3,
            target_reps: '8-10',
            target_rpe: '8-9',
            rest_seconds: 150,
            notes: 'Maintain a neutral lower back, set your hips back, don\'t allow your spine to round',
          },
          {
            name: 'Walking Lunge',
            muscle_group: 'Quads',
            warmup_sets: 1,
            working_sets: 2,
            target_reps: '10',
            target_rpe: '8-9',
            rest_seconds: 150,
            notes: 'Take medium strides, minimize the amount you push off your rear leg',
          },
          {
            name: 'Seated Leg Curl',
            muscle_group: 'Hamstrings',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '10-12',
            target_rpe: '9-10',
            rest_seconds: 90,
            notes: 'Focus on squeezing your hamstrings to move the weight',
          },
          {
            name: 'Leg Press Toe Press',
            muscle_group: 'Calves',
            warmup_sets: 1,
            working_sets: 4,
            target_reps: '10-12',
            target_rpe: '9-10',
            rest_seconds: 90,
            notes: 'Press all the way up to your toes, stretch your calves at the bottom, don\'t bounce',
          },
          {
            name: 'Decline Plate-Weighted Crunch',
            muscle_group: 'Abs',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '10-12',
            target_rpe: '9-10',
            rest_seconds: 90,
            notes: 'Hold a plate or DB to your chest and crunch hard!',
          },
        ],
      },
      {
        name: 'Upper #1',
        day_type: 'upper',
        exercises: [
          {
            name: 'Pull-Up',
            muscle_group: 'Back',
            warmup_sets: 2,
            working_sets: 2,
            target_reps: '8-10',
            target_rpe: '8-9',
            rest_seconds: 150,
            notes: '1.5x shoulder width grip, pull your chest to the bar',
          },
          {
            name: 'Close-Grip Barbell Incline Press',
            muscle_group: 'Chest',
            warmup_sets: 2,
            working_sets: 3,
            target_reps: '8, 5, 12',
            target_rpe: '8-9',
            rest_seconds: 210,
            notes: 'Use ~45° incline and a grip width just outside shoulder width',
          },
          {
            name: 'Kroc Row',
            muscle_group: 'Back',
            warmup_sets: 2,
            working_sets: 3,
            target_reps: '10-12',
            target_rpe: '8-9',
            rest_seconds: 150,
            notes: 'Kroc rows are basically just a dumbbell row with mild cheating and a slightly more upright posture. Don\'t be afraid to go heavy and use straps if your grip is limiting',
          },
          {
            name: 'Cable Lateral Raise (Eccentric + Constant Tension)',
            muscle_group: 'Shoulders',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '5 + 15',
            target_rpe: '9-10',
            rest_seconds: 90,
            notes: 'First 5 reps: 5-second lowering phase, last 15 reps constant tension (no pausing at the bottom or top)',
          },
          {
            name: 'N1-Style Cross-Body Bicep Curl',
            muscle_group: 'Biceps',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '10-12',
            target_rpe: '9-10',
            rest_seconds: 90,
            notes: 'Curl across your body with your arm out to the side at ~60°',
          },
          {
            name: 'Diamond Pushup',
            muscle_group: 'Triceps',
            warmup_sets: 0,
            working_sets: 1,
            target_reps: 'AMRAP',
            target_rpe: '10',
            rest_seconds: 0,
            notes: 'Place your hands close together on the ground so that they form a diamond shape and do as many pushups as possible with a smooth tempo',
          },
        ],
      },
      {
        name: 'Lower #1',
        day_type: 'lower',
        exercises: [
          {
            name: 'Deadlift',
            muscle_group: 'Back',
            warmup_sets: 3,
            working_sets: 1,
            target_reps: '5',
            target_rpe: '8-9',
            rest_seconds: 240,
            notes: 'Brace your lats, chest tall, pull the slack out of the bar before lifting',
          },
          {
            name: 'Stiff-Leg Deadlift',
            muscle_group: 'Hamstrings',
            warmup_sets: 0,
            working_sets: 2,
            target_reps: '8',
            target_rpe: '8-9',
            rest_seconds: 210,
            notes: 'Think about doing a high-hip conventional deadlift with a slight bend in the knees',
          },
          {
            name: 'Leg Press',
            muscle_group: 'Quads',
            warmup_sets: 2,
            working_sets: 4,
            target_reps: '10-12',
            target_rpe: '8-9',
            rest_seconds: 150,
            notes: 'Medium width feet placement on the platform, don\'t allow your lower back to round',
          },
          {
            name: 'Glute Ham Raise',
            muscle_group: 'Hamstrings',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '8-10',
            target_rpe: '9-10',
            rest_seconds: 90,
            notes: 'Keep your hips straight, do Nordic ham curls if no GHR machine',
          },
          {
            name: 'Slow-Eccentric Leg Extension',
            muscle_group: 'Quads',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '8-10',
            target_rpe: '9-10',
            rest_seconds: 90,
            notes: 'Control the weight with a 3-4 second negative',
          },
          {
            name: 'Seated Calf Raise',
            muscle_group: 'Calves',
            warmup_sets: 1,
            working_sets: 4,
            target_reps: '15-20',
            target_rpe: '9-10',
            rest_seconds: 90,
            notes: 'Press all the way up to your toes, stretch your calves at the bottom, don\'t bounce',
          },
          {
            name: 'Roman Chair Leg Raise',
            muscle_group: 'Abs',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '10-20',
            target_rpe: '9-10',
            rest_seconds: 90,
            notes: 'Don\'t swing your legs at the bottom, minimize momentum, tuck your knees towards your chest if lifting your legs straight out is too challenging',
          },
        ],
      },
    ],
  },
  {
    name: 'Phase 2',
    description: 'Maximum Effort (Low Volume, High Intensity)',
    workouts: [
      {
        name: 'Push #1',
        day_type: 'push',
        exercises: [
          {
            name: 'Bench Press',
            muscle_group: 'Chest',
            warmup_sets: 3,
            working_sets: 1,
            target_reps: '3-5',
            target_rpe: '8-9',
            rest_seconds: 240,
            notes: 'Set up a comfortable arch, quick pause on the chest and explode up on each rep',
          },
          {
            name: 'High-Incline Smith Machine Press',
            muscle_group: 'Chest',
            warmup_sets: 2,
            working_sets: 2,
            target_reps: '4-6',
            target_rpe: '10',
            rest_seconds: 210,
            notes: 'Set the bench at a 45-60 degree incline, touch the bar to your upper chest with control',
          },
          {
            name: 'Egyptian Cable Lateral Raise',
            muscle_group: 'Shoulders',
            warmup_sets: 2,
            working_sets: 2,
            target_reps: '6-8',
            target_rpe: '10',
            rest_seconds: 150,
            notes: 'Lean away from the cable. Focus on squeezing your delts.',
          },
          {
            name: 'Overhead Cable Triceps Extension',
            muscle_group: 'Triceps',
            warmup_sets: 2,
            working_sets: 2,
            target_reps: '4-6',
            target_rpe: '10',
            rest_seconds: 150,
            notes: 'Do both arms at once, resist the negative',
          },
          {
            name: 'Cable Triceps Kickback',
            muscle_group: 'Triceps',
            warmup_sets: 1,
            working_sets: 2,
            target_reps: '6-8',
            target_rpe: '10',
            rest_seconds: 150,
            notes: 'Lean slightly forward, lock your elbow behind your torso (shoulder hyperextension)',
          },
        ],
      },
      {
        name: 'Pull #1',
        day_type: 'pull',
        exercises: [
          {
            name: 'Neutral-Grip Lat Pulldown',
            muscle_group: 'Back',
            warmup_sets: 3,
            working_sets: 3,
            target_reps: '4-6',
            target_rpe: '10',
            rest_seconds: 210,
            notes: 'Pull your elbows down against your sides',
          },
          {
            name: 'Pendlay Row',
            muscle_group: 'Back',
            warmup_sets: 3,
            working_sets: 2,
            target_reps: '4-6',
            target_rpe: '10',
            rest_seconds: 210,
            notes: 'Initiate the movement by squeezing your shoulder blades together, pull to your lower chest, avoid using momentum',
          },
          {
            name: 'Reverse Pec Deck',
            muscle_group: 'Rear Delts',
            warmup_sets: 2,
            working_sets: 2,
            target_reps: '6-8',
            target_rpe: '10',
            rest_seconds: 150,
            notes: 'Swing the weight "out", not "back"',
          },
          {
            name: 'EZ-Bar Curl',
            muscle_group: 'Biceps',
            warmup_sets: 2,
            working_sets: 2,
            target_reps: '4-6',
            target_rpe: '10',
            rest_seconds: 150,
            notes: 'Arc the bar "out" not "up", focus on squeezing your biceps',
          },
          {
            name: 'Hammer Cheat Curl',
            muscle_group: 'Biceps',
            warmup_sets: 1,
            working_sets: 1,
            target_reps: '4-6',
            target_rpe: '10',
            rest_seconds: 0,
            notes: 'You can use slight momentum on the concentric, but control the eccentric with your elbows stationary',
          },
        ],
      },
      {
        name: 'Legs #1',
        day_type: 'legs',
        exercises: [
          {
            name: 'Squat or Machine Squat',
            muscle_group: 'Quads',
            warmup_sets: 3,
            working_sets: 1,
            target_reps: '3-5',
            target_rpe: '8-9',
            rest_seconds: 240,
            notes: 'Sit back and down, keep your upper back tight to the bar',
          },
          {
            name: 'Barbell RDL',
            muscle_group: 'Hamstrings',
            warmup_sets: 3,
            working_sets: 2,
            target_reps: '4-6',
            target_rpe: '10',
            rest_seconds: 210,
            notes: 'Maintain a neutral lower back, set your hips back, don\'t allow your spine to round',
          },
          {
            name: 'Leg Extension',
            muscle_group: 'Quads',
            warmup_sets: 2,
            working_sets: 2,
            target_reps: '6-8',
            target_rpe: '10',
            rest_seconds: 150,
            notes: 'Focus on squeezing your quads to make the weight move.',
          },
          {
            name: 'Seated Calf Raise',
            muscle_group: 'Calves',
            warmup_sets: 2,
            working_sets: 2,
            target_reps: '4-6',
            target_rpe: '10',
            rest_seconds: 150,
            notes: 'Press all the way up to your toes, stretch your calves at the bottom, don\'t bounce',
          },
          {
            name: 'Cable Crunch',
            muscle_group: 'Abs',
            warmup_sets: 2,
            working_sets: 2,
            target_reps: '6-8',
            target_rpe: '10',
            rest_seconds: 150,
            notes: 'Round your back as you crunch',
          },
        ],
      },
      {
        name: 'Upper #1',
        day_type: 'upper',
        exercises: [
          {
            name: 'Wide-Grip Pull-Up',
            muscle_group: 'Back',
            warmup_sets: 3,
            working_sets: 2,
            target_reps: '4-6',
            target_rpe: '10',
            rest_seconds: 210,
            notes: 'Use ~1.5x shoulder width grip. Add weight or use assistance as needed to hit RPE. Keep form as consistent as possible.',
          },
          {
            name: 'Seated DB Shoulder Press',
            muscle_group: 'Shoulders',
            warmup_sets: 3,
            working_sets: 2,
            target_reps: '6-8',
            target_rpe: '10',
            rest_seconds: 210,
            notes: 'Bring the dumbbells all the way down, keep your torso upright',
          },
          {
            name: 'Close-Grip Seated Cable Row',
            muscle_group: 'Back',
            warmup_sets: 3,
            working_sets: 1,
            target_reps: '4-6',
            target_rpe: '10',
            rest_seconds: 210,
            notes: 'Focus on squeezing your shoulder blades together, drive your elbows down and back.',
          },
          {
            name: 'Weighted Dip',
            muscle_group: 'Chest',
            warmup_sets: 3,
            working_sets: 2,
            target_reps: '4-6',
            target_rpe: '10',
            rest_seconds: 210,
            notes: 'Tuck your elbows at 45°, lean your torso forward 15°, shoulder width or slightly wider grip',
          },
          {
            name: 'Machine Lateral Raise',
            muscle_group: 'Shoulders',
            warmup_sets: 2,
            working_sets: 2,
            target_reps: '6-8',
            target_rpe: '10',
            rest_seconds: 150,
            notes: 'Focus on squeezing your lateral delt to move the weight',
          },
          {
            name: 'Alternating DB Curl',
            muscle_group: 'Biceps',
            warmup_sets: 2,
            working_sets: 1,
            target_reps: '4-6',
            target_rpe: '10',
            rest_seconds: 150,
            notes: 'Alternate arms with each curl: do 1 rep with your right arm, one rep with your left arm. Repeat until you reach 4-6 reps with each arm.',
          },
          {
            name: 'Triceps Pressdown',
            muscle_group: 'Triceps',
            warmup_sets: 2,
            working_sets: 1,
            target_reps: '4-6',
            target_rpe: '10',
            rest_seconds: 0,
            notes: 'Focus on squeezing your triceps to move the weight',
          },
        ],
      },
      {
        name: 'Lower #1',
        day_type: 'lower',
        exercises: [
          {
            name: 'Hack Squat',
            muscle_group: 'Quads',
            warmup_sets: 3,
            working_sets: 2,
            target_reps: '4-6',
            target_rpe: '9-10',
            rest_seconds: 240,
            notes: 'Allow your knees to come forward (past your toes), focus the tension on your quads',
          },
          {
            name: 'Dumbbell Walking Lunge',
            muscle_group: 'Quads',
            warmup_sets: 3,
            working_sets: 2,
            target_reps: '4-6',
            target_rpe: '10',
            rest_seconds: 210,
            notes: 'Do 4-6 reps with each leg (10-12 total strides). Straps may be helpful if your grip becomes limiting.',
          },
          {
            name: 'Seated Leg Curl',
            muscle_group: 'Hamstrings',
            warmup_sets: 2,
            working_sets: 2,
            target_reps: '4-6',
            target_rpe: '10',
            rest_seconds: 150,
            notes: 'Focus on squeezing your hamstrings to move the weight',
          },
          {
            name: 'Standing Calf Raise',
            muscle_group: 'Calves',
            warmup_sets: 2,
            working_sets: 2,
            target_reps: '6-8',
            target_rpe: '10',
            rest_seconds: 150,
            notes: 'Press all the way up to your toes, stretch your calves at the bottom, don\'t bounce',
          },
          {
            name: 'Decline Plate-Weighted Crunch',
            muscle_group: 'Abs',
            warmup_sets: 2,
            working_sets: 2,
            target_reps: '6-8',
            target_rpe: '10',
            rest_seconds: 150,
            notes: 'Hold a plate or DB to your chest and crunch hard!',
          },
        ],
      },
    ],
  },
  {
    name: 'Phase 3',
    description: 'Supercompensation (High Volume, Moderate Intensity)',
    workouts: [
      {
        name: 'Push #1',
        day_type: 'push',
        exercises: [
          {
            name: 'Low Incline DB Press',
            muscle_group: 'Chest',
            warmup_sets: 2,
            working_sets: 3,
            target_reps: '20',
            target_rpe: '9',
            rest_seconds: 150,
            notes: '15° bench angle, tuck your elbows on the negative, flare as you press',
          },
          {
            name: 'Machine Shoulder Press',
            muscle_group: 'Shoulders',
            warmup_sets: 2,
            working_sets: 3,
            target_reps: '15',
            target_rpe: '9',
            rest_seconds: 150,
            notes: "Don't stop in between reps, keep smooth and controlled tension on the delts",
          },
          {
            name: 'Cable Crossover Ladder',
            muscle_group: 'Chest',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '20',
            target_rpe: '10',
            rest_seconds: 90,
            notes: 'Do one set with low cable position, one set with medium-height cable position, and one set with a high cable position',
          },
          {
            name: 'A1: Lean-In DB Lateral Raise',
            muscle_group: 'Shoulders',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '15',
            target_rpe: '10',
            rest_seconds: 0,
            notes: "Lean into a bench and do lateral raises. Keep tension - don't rest your arm against your side at the bottom.",
            is_superset: 1,
            superset_group: 'A',
          },
          {
            name: 'A2: Side Delt Static Stretch',
            muscle_group: 'Shoulders',
            warmup_sets: 0,
            working_sets: 3,
            target_reps: '30s HOLD',
            target_rpe: '7',
            rest_seconds: 90,
            notes: 'Hold a side delt stretch for 30 seconds. The stretch should be held at about a 7/10 intensity.',
            is_superset: 1,
            superset_group: 'A',
          },
          {
            name: 'Overhead Triceps Extension',
            muscle_group: 'Triceps',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '20',
            target_rpe: '10',
            rest_seconds: 90,
            notes: 'Do both arms at once, resist the negative',
          },
          {
            name: 'Med-Ball Close Grip Push Up',
            muscle_group: 'Triceps',
            warmup_sets: 0,
            working_sets: 1,
            target_reps: 'AMRAP',
            target_rpe: '10',
            rest_seconds: 0,
            notes: 'Place your hands on a medicine ball and do smooth, controlled pushups',
          },
        ],
      },
      {
        name: 'Pull #1',
        day_type: 'pull',
        exercises: [
          {
            name: '1-Arm Half Kneeling Lat Pulldown',
            muscle_group: 'Back',
            warmup_sets: 1,
            working_sets: 2,
            target_reps: '20',
            target_rpe: '9',
            rest_seconds: 90,
            notes: 'Keep chest tall, keep elbow tucked in close to your torso, focus on squeezing your lat to move the weight',
          },
          {
            name: 'Omni-Grip Lat Pulldown',
            muscle_group: 'Back',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '20',
            target_rpe: '9',
            rest_seconds: 150,
            notes: 'One set wide grip (overhand), 1 set middle grip (overhand), 1 set close grip (underhand)',
          },
          {
            name: 'Machine Low Row',
            muscle_group: 'Back',
            warmup_sets: 2,
            working_sets: 4,
            target_reps: '20',
            target_rpe: '9',
            rest_seconds: 150,
            notes: 'Focus on squeezing your shoulder blades together on each rep',
          },
          {
            name: 'Cable Shrug-In',
            muscle_group: 'Traps',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '20',
            target_rpe: '10',
            rest_seconds: 90,
            notes: 'Set up two cable handles low and shrug up and in. Squeeze your upper traps to move the weight.',
          },
          {
            name: 'Reverse Pec Deck',
            muscle_group: 'Rear Delts',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '20',
            target_rpe: '10',
            rest_seconds: 90,
            notes: 'Swing the weight "out", not "back"',
          },
          {
            name: 'EZ-Bar Curl (Heavy)',
            muscle_group: 'Biceps',
            warmup_sets: 2,
            working_sets: 1,
            target_reps: '4-6',
            target_rpe: '9',
            rest_seconds: 90,
            notes: 'Arc the bar "out" not "up", focus on squeezing your biceps',
          },
          {
            name: "A1: EZ-Bar Bicep 21's",
            muscle_group: 'Biceps',
            warmup_sets: 0,
            working_sets: 2,
            target_reps: '21',
            target_rpe: '10',
            rest_seconds: 0,
            notes: '7 reps seated, 7 reps standing full ROM, 7 reps bottom-half curls',
            is_superset: 1,
            superset_group: 'A',
          },
          {
            name: 'A2: Bicep Static Stretch',
            muscle_group: 'Biceps',
            warmup_sets: 0,
            working_sets: 2,
            target_reps: '30s HOLD',
            target_rpe: '7',
            rest_seconds: 90,
            notes: 'Hold a bicep stretch for 30 seconds. The stretch should be held at about a 7/10 intensity.',
            is_superset: 1,
            superset_group: 'A',
          },
        ],
      },
      {
        name: 'Legs #1',
        day_type: 'legs',
        exercises: [
          {
            name: 'Front Squat',
            muscle_group: 'Quads',
            warmup_sets: 2,
            working_sets: 3,
            target_reps: '15',
            target_rpe: '7-8',
            rest_seconds: 150,
            notes: "These will be challenging, let's push! Don't go so heavy that you miss reps. Be humble with your weight and focus on keeping your torso upright",
          },
          {
            name: 'Dumbbell RDL',
            muscle_group: 'Hamstrings',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '20',
            target_rpe: '9',
            rest_seconds: 150,
            notes: 'Emphasize the stretch in your hamstrings, prevent your lower back from rounding',
          },
          {
            name: 'Walking Lunge',
            muscle_group: 'Quads',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '10',
            target_rpe: '9',
            rest_seconds: 150,
            notes: 'Take medium strides, minimize the amount you push off your rear leg',
          },
          {
            name: 'Slow Seated Leg Curl (3s up, 3s down)',
            muscle_group: 'Hamstrings',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '8',
            target_rpe: '10',
            rest_seconds: 90,
            notes: 'Lift with a slow tempo. The positive should take 3 seconds and the negative should take 3 seconds.',
          },
          {
            name: 'Leg Press Toe Press',
            muscle_group: 'Calves',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '20',
            target_rpe: '10',
            rest_seconds: 90,
            notes: "Press all the way up to your toes, stretch your calves at the bottom, don't bounce",
          },
          {
            name: 'LLPT Plank',
            muscle_group: 'Abs',
            warmup_sets: 0,
            working_sets: 3,
            target_reps: '20',
            target_rpe: '10',
            rest_seconds: 90,
            notes: 'Contract your glutes and position your elbows under your eyes to make the plank more difficult',
          },
        ],
      },
      {
        name: 'Upper #1',
        day_type: 'upper',
        exercises: [
          {
            name: 'Bench Press (Top Set)',
            muscle_group: 'Chest',
            warmup_sets: 3,
            working_sets: 1,
            target_reps: '2-4',
            target_rpe: '8-9',
            rest_seconds: 210,
            notes: 'Set up a comfortable arch, quick pause on the chest and explode up on each rep',
          },
          {
            name: 'Bench Press (Back Off AMRAP)',
            muscle_group: 'Chest',
            warmup_sets: 0,
            working_sets: 1,
            target_reps: 'AMRAP',
            target_rpe: '10',
            rest_seconds: 210,
            notes: 'Use ~60% of the weight you used on your top set and do it for as many reps as possible. You should be in the range of 10-20+ reps on this set! Use a spotter and safety bars!',
          },
          {
            name: 'Pull-Up (Cluster Sets)',
            muscle_group: 'Back',
            warmup_sets: 2,
            working_sets: 6,
            target_reps: '3',
            target_rpe: '7-8',
            rest_seconds: 15,
            notes: '6 cluster sets: 3 reps, rest 15s, repeat 6x. Keep form smooth and controlled.',
          },
          {
            name: 'Standing Dumbbell Arnold Press',
            muscle_group: 'Shoulders',
            warmup_sets: 2,
            working_sets: 3,
            target_reps: '15',
            target_rpe: '9',
            rest_seconds: 150,
            notes: 'Start with your elbows in front of you and palms facing in. Rotate the dumbbells so that your palms face forward as you press.',
          },
          {
            name: 'Wide-Grip Cable Row (Cluster Sets)',
            muscle_group: 'Back',
            warmup_sets: 2,
            working_sets: 10,
            target_reps: '3',
            target_rpe: '7-8',
            rest_seconds: 15,
            notes: '10 cluster sets: 3 reps, rest 15s, repeat 10x. Keep form tight.',
          },
          {
            name: 'Triceps Pressdown',
            muscle_group: 'Triceps',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '20',
            target_rpe: '10',
            rest_seconds: 90,
            notes: 'Focus on squeezing your triceps to move the weight',
          },
          {
            name: 'Bayesian Cable Curl',
            muscle_group: 'Biceps',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '20',
            target_rpe: '10',
            rest_seconds: 90,
            notes: 'Keep your elbow behind your torso throughout the range of motion, focus on squeezing your bicep. Sets are per arm',
          },
        ],
      },
      {
        name: 'Lower #1',
        day_type: 'lower',
        exercises: [
          {
            name: 'Deadlift',
            muscle_group: 'Back',
            warmup_sets: 3,
            working_sets: 2,
            target_reps: '8',
            target_rpe: '9',
            rest_seconds: 210,
            notes: 'Brace your lats, chest tall, pull the slack out of the bar before lifting',
          },
          {
            name: 'Leg Press',
            muscle_group: 'Quads',
            warmup_sets: 2,
            working_sets: 2,
            target_reps: '20',
            target_rpe: '9',
            rest_seconds: 150,
            notes: "Medium width feet placement on the platform, don't allow your lower back to round",
          },
          {
            name: 'Leg Extension',
            muscle_group: 'Quads',
            warmup_sets: 1,
            working_sets: 5,
            target_reps: '20',
            target_rpe: '10',
            rest_seconds: 90,
            notes: 'Focus on squeezing your quads to make the weight move',
          },
          {
            name: 'Lying Leg Curl',
            muscle_group: 'Hamstrings',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '20',
            target_rpe: '10',
            rest_seconds: 90,
            notes: 'Focus on squeezing your hamstrings to make the weight move',
          },
          {
            name: 'Seated Calf Raise',
            muscle_group: 'Calves',
            warmup_sets: 1,
            working_sets: 3,
            target_reps: '20',
            target_rpe: '10',
            rest_seconds: 90,
            notes: "Press all the way up to your toes, stretch your calves at the bottom, don't bounce",
          },
          {
            name: 'Corpse Crunch',
            muscle_group: 'Abs',
            warmup_sets: 0,
            working_sets: 3,
            target_reps: '20',
            target_rpe: '10',
            rest_seconds: 90,
            notes: 'Clear your upper back off the floor when you crunch, hold for 1-2 seconds and then go back down. Don\'t yank with your neck.',
          },
        ],
      },
    ],
  },
];
